CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  email VARCHAR(40) NOT NULL UNIQUE,
  password VARCHAR(40) NOT NULL,
  activation_status VARCHAR(10) NOT NULL,
  activation_link VARCHAR(40) NOT NULL,
  registration_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tokens (
  user_id VARCHAR(255) NOT NULL UNIQUE,
  refresh_token VARCHAR(255) NOT NULL
);
